openapi: 3.1.0
info:
  title: additionalProperties example
  description: Demonstrate how to use additionalProperties
  version: 1.0.0
paths:
  /animals/{id}:
    get:
      summary: Find animal by ID
      description: Returns a single animal
      operationId: getAnimalByID
      parameters:
      - name: id
        in: path
        description: ID of animal to get
        schema:
          type: string
        required: true
        example: "10"
      responses:
        "200":
          description: successful operation
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/Dog'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: animal not found
          content: {}
components:
  schemas:
    Dog:
      type: object
      required:
        - name
        - owner
        - bark
      properties:
        name:
          type: string
        owner:
          type: string
        bark:
          type: string
        detail: # <- this is the property we wish to allow anything
          $ref: "#/components/schemas/AnyJSONObject"
            
    # Workaround definitions to accept any JSON
    AnyJSON:
      anyOf: 
        - type: 'null'
        - type: string
        - type: number
        - type: boolean
        - $ref: '#/components/schemas/JSONArray'
    JSONArray:
      type: array
      items: 
        anyOf: 
          -  $ref: "#/components/schemas/AnyJSON"       # Array can accept any primitive
          -  $ref: "#/components/schemas/AnyJSONObject" # or an object with any type 
    AnyJSONObject:
      type: object
      additionalProperties: 
        $ref: "#/components/schemas/AnyJSON"          